=== Vadimka29/genetic-scheduller/src/main/resources/testdata/schema/work-item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns:scheduler="scheduler"
           targetNamespace="scheduler">

    <xs:element name="subjects">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="subject" type="scheduler:subject" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="subject">
        <xs:sequence>
            <xs:element name="completion-type" type="scheduler:completion-type"/>
            <xs:element name="priority" type="scheduler:priority"/>
            <xs:element name="pass-day" type="scheduler:pass-day" minOccurs="1" maxOccurs="5"/>
            <xs:element name="subject-item" type="scheduler:subject-item" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="subject-item">
        <xs:sequence>
            <xs:element name="work-name" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="work-type" type="scheduler:subjectitem-type"/>
            <xs:element name="duration" type="scheduler:hours-count"/>
            <xs:element name="hours-per-day" type="scheduler:hours-count" default="2"/>
            <xs:element name="retrieve-date" type="xs:date"/>
            <xs:element name="deadline" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="hours-count">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="subjectitem-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="lab-work"/>
            <xs:enumeration value="rgr"/>
            <xs:enumeration value="course-work"/>
            <xs:enumeration value="home-work"/>
            <xs:enumeration value="additional-work"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="completion-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="credit"/>
            <xs:enumeration value="differentiated-credit"/>
            <xs:enumeration value="exam"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="priority">
        <xs:restriction base="xs:string">
            <xs:enumeration value="low"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="high"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="pass-day">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Monday"/>
            <xs:enumeration value="Tuesday"/>
            <xs:enumeration value="Wednesday"/>
            <xs:enumeration value="Thursday"/>
            <xs:enumeration value="Friday"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Vadimka29/genetic-scheduller/src/main/resources/testdata/test-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<subjects
        xmlns="scheduler"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="/schema/work-item.xsd">

    <subject name="Decision Theory">
        <completion-type>differentiated-credit</completion-type>
        <priority>medium</priority>
        <pass-day>Monday</pass-day>
        <pass-day>Friday</pass-day>

        <subject-item>
            <work-name>LabWork №1</work-name>
            <description>First lab work from TSPP subject</description>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2015-09-24</retrieve-date>
            <deadline>2016-10-22</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №2</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-10-22</retrieve-date>
            <deadline>2016-11-19</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №3</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-11-19</retrieve-date>
            <deadline>2016-12-17</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №4</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-12-17</retrieve-date>
            <deadline>2016-12-31</deadline>
        </subject-item>
    </subject>

    <subject name="Complex systems modeling">
        <completion-type>exam</completion-type>
        <priority>high</priority>
        <pass-day>Tuesday</pass-day>
        <pass-day>Thursday</pass-day>

        <subject-item>
            <work-name>LabWork №1</work-name>
            <description>First lab work from ComplexSystemModeling subject</description>
            <work-type>lab-work</work-type>
            <duration>5</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-09-01</retrieve-date>
            <deadline>2016-09-16</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №2</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-09-16</retrieve-date>
            <deadline>2016-09-30</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №3</work-name>
            <work-type>lab-work</work-type>
            <duration>3</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-09-30</retrieve-date>
            <deadline>2016-10-21</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №4</work-name>
            <work-type>lab-work</work-type>
            <duration>5</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-10-21</retrieve-date>
            <deadline>2016-10-28</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №5</work-name>
            <work-type>lab-work</work-type>
            <duration>5</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-10-28</retrieve-date>
            <deadline>2016-11-11</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №6</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-11-11</retrieve-date>
            <deadline>2016-11-25</deadline>
        </subject-item>
        <subject-item>
            <work-name>Course work</work-name>
            <work-type>course-work</work-type>
            <duration>30</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-11-19</retrieve-date>
            <deadline>2016-12-31</deadline>
        </subject-item>
    </subject>
    
    <subject name="Computer Networks">
        <completion-type>exam</completion-type>
        <priority>high</priority>
        <pass-day>Wednesday</pass-day>

        <subject-item>
            <work-name>LabWork №1</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-09-01</retrieve-date>
            <deadline>2016-10-09</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №2</work-name>
            <work-type>lab-work</work-type>
            <duration>5</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-10-09</retrieve-date>
            <deadline>2016-10-23</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №3</work-name>
            <work-type>lab-work</work-type>
            <duration>3</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-10-23</retrieve-date>
            <deadline>2016-11-06</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №4</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-11-06</retrieve-date>
            <deadline>2016-11-20</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №5</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-11-20</retrieve-date>
            <deadline>2016-12-04</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №6</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-12-04</retrieve-date>
            <deadline>2016-12-18</deadline>
        </subject-item>
        <subject-item>
            <work-name>Computer Network RGR</work-name>
            <work-type>rgr</work-type>
            <duration>18</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-12-04</retrieve-date>
            <deadline>2016-12-30</deadline>
        </subject-item>
    </subject>

    <subject name="IT Project Management">
        <completion-type>credit</completion-type>
        <priority>medium</priority>
        <pass-day>Friday</pass-day>

        <subject-item>
            <work-name>LabWork №1</work-name>
            <work-type>lab-work</work-type>
            <duration>2</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-09-10</retrieve-date>
            <deadline>2016-10-08</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №2</work-name>
            <work-type>lab-work</work-type>
            <duration>1</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-10-08</retrieve-date>
            <deadline>2016-11-05</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №3</work-name>
            <work-type>lab-work</work-type>
            <duration>3</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-11-05</retrieve-date>
            <deadline>2016-12-03</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №4</work-name>
            <work-type>lab-work</work-type>
            <duration>4</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-12-03</retrieve-date>
            <deadline>2016-12-31</deadline>
        </subject-item>
    </subject>

    <subject name="Information systems design">
        <completion-type>credit</completion-type>
        <priority>medium</priority>
        <pass-day>Friday</pass-day>
        <subject-item>
            <work-name>LabWork №1</work-name>
            <work-type>lab-work</work-type>
            <duration>2</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-09-01</retrieve-date>
            <deadline>2016-09-15</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №2</work-name>
            <work-type>lab-work</work-type>
            <duration>1</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-09-15</retrieve-date>
            <deadline>2016-10-01</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №3</work-name>
            <work-type>lab-work</work-type>
            <duration>2</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-10-01</retrieve-date>
            <deadline>2016-10-20</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №4</work-name>
            <work-type>lab-work</work-type>
            <duration>3</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-10-20</retrieve-date>
            <deadline>2016-11-05</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №5</work-name>
            <work-type>lab-work</work-type>
            <duration>2</duration>
            <hours-per-day></hours-per-day>
            <retrieve-date>2016-11-05</retrieve-date>
            <deadline>2016-12-01</deadline>
        </subject-item>
        <subject-item>
            <work-name>LabWork №6</work-name>
            <work-type>lab-work</work-type>
            <duration>2</duration>
